// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFyNKKxrG-ZQ0dYMqMKgBtCqblTVNVgbQ',
    appId: '1:343116099696:web:f136c6c4bf057edef184b5',
    messagingSenderId: '343116099696',
    projectId: 'ehr-management-52c95',
    authDomain: 'ehr-management-52c95.firebaseapp.com',
    storageBucket: 'ehr-management-52c95.appspot.com',
    measurementId: 'G-RN40FEC8ZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCefZHPfLQpMv8aT8az0p_BQdEc7hzDXAM',
    appId: '1:343116099696:android:e1c587b0608ca80ff184b5',
    messagingSenderId: '343116099696',
    projectId: 'ehr-management-52c95',
    storageBucket: 'ehr-management-52c95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxfpQPGeSfqIBWSWXu1Jj9uvn4mKYAoL8',
    appId: '1:343116099696:ios:43588898a3ed2215f184b5',
    messagingSenderId: '343116099696',
    projectId: 'ehr-management-52c95',
    storageBucket: 'ehr-management-52c95.appspot.com',
    iosBundleId: 'com.example.ehrManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxfpQPGeSfqIBWSWXu1Jj9uvn4mKYAoL8',
    appId: '1:343116099696:ios:acfd4d8a47b36e3cf184b5',
    messagingSenderId: '343116099696',
    projectId: 'ehr-management-52c95',
    storageBucket: 'ehr-management-52c95.appspot.com',
    iosBundleId: 'com.example.ehrManagement.RunnerTests',
  );
}
